### ISSUE TITLE
net-analyzer/nmap-7.95 fails to compile with LibreSSL 4.1.0 emake failed

### ISSUE THREAD

**Issue by blucybrb14de** [gentoo/libressl#596]
Hello,

It appears when attempting to emerge nmap::libressl, this error shows up:

```
nse_ssl_cert.cc:496:36: error: use of undeclared identifier 'EC_GROUP_method_of'
  496 |     nid = EC_METHOD_get_field_type(EC_GROUP_method_of(group));
      |                                    ^
1 error generated.
make: *** [Makefile:119: nse_ssl_cert.o] Error 1
make: *** Waiting for unfinished jobs....
```

This error does not seem to be related to musl or any other compiler options.

[inxi-output.log](https://github.com/user-attachments/files/20717218/inxi-output.log)

[build.log](https://github.com/user-attachments/files/20717221/build.log)

**Comment by orbea** [comment]
I pushed a fix, but please let me know if you have any runtime issues that seem related to the patch. Thanks for reporting.
