### ISSUE TITLE
app-crypt/qca::libressl fails with LibreSSL 4.0.0

### ISSUE THREAD

**Issue by blucybrb14de** [gentoo/libressl#574]
Similarly,  it looks like app-crypt/qca::libressl fails to compile with LibreSSL 4.0.0, 
due to an undeclared identifier. 

dev-libs/libressl: ```LibreSSL 4.0.0```

app-crypt/qca: ```app-crypt/qca-2.3.9```

[qca-2.3.9.log](https://github.com/user-attachments/files/17402528/qca-2.3.9.log)

[inxi-output.log](https://github.com/user-attachments/files/17402533/inxi-output.log)

Error Message: 
```
/usr/lib64/qt6/mkspecs/linux-clang  -O3 -pipe -march=alderlake  -mno-cldemote -mno-kl -mno-sgx -mno-widekl -mshstk  -flto=thin -fPIC -fplugin=LLVMPolly.so -mllvm -polly -mtune=alderlake -falign-functions=32 -Wcast-align -Wnon-virtual-dtor -Wno-long-long -Wundef -Wchar-subscripts -Wall -W -Wpointer-arith -Wwrite-strings -Wformat-security -fno-check-new -fno-common -std=gnu++17 -fPIC -fPIC -MD -MT plugins/qca-ossl/CMakeFiles/qca-ossl.dir/qca-ossl.cpp.o -MF plugins/qca-ossl/CMakeFiles/qca-ossl.dir/qca-ossl.cpp.o.d -o plugins/qca-ossl/CMakeFiles/qca-ossl.dir/qca-ossl.cpp.o -c /var/tmp/portage/app-crypt/qca-2.3.9/work/qca-2.3.9/plugins/qca-ossl/qca-ossl.cpp
/var/tmp/portage/app-crypt/qca-2.3.9/work/qca-2.3.9/plugins/qca-ossl/qca-ossl.cpp:6949:47: error: use of undeclared identifier 'EVP_whirlpool'
 6949 |                 return new opensslHashContext(EVP_whirlpool(), this, type);
      |                                               ^
1 error generated.
[59/61] /usr/lib/llvm/19/bin/clang++ -DQCA_SYSTEMSTORE_PATH=\"/etc/ssl/certs/ca-certificates.crt\" -DQT_CORE_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_SIGNALS_SLOTS_KEYWORDS -DQT_NO_URL_CAST_FROM_STRING -DQT_STRICT_ITERATORS -DQT_USE_QSTRINGBUILDER -D_DEFAULT_SOURCE -I/var/tmp/portage/app-crypt/qca-2.3.9/work/qca-2.3.9_build-qt6/tools/qcatool -I/var/tmp/portage/app-crypt/qca-2.3.9/work/qca-2.3.9/tools/qcatool -I/var/tmp/portage/app-crypt/qca-2.3.9/work/qca-2.3.9_build-qt6/tools/qcatool/qcatool-qt6_autogen/include -I/var/tmp/portage/app-crypt/qca-2.3.9/work/qca-2.3.9/include/QtCrypto -I/var/tmp/portage/app-crypt/qca-2.3.9/work/qca-2.3.9_build-qt6 -isystem /usr/include/qt6/QtCore -isystem /usr/include/qt6 -isystem /usr/lib64/qt6/mkspecs/linux-clang  -O3 -pipe -march=alderlake  -mno-cldemote -mno-kl -mno-sgx -mno-widekl -mshstk  -flto=thin -fPIC -fplugin=LLVMPolly.so -mllvm -polly -mtune=alderlake -falign-functions=32 -Wcast-align -Wnon-virtual-dtor -Wno-long-long -Wundef -Wchar-subscripts -Wall -W -Wpointer-arith -Wwrite-strings -Wformat-security -fno-check-new -fno-common  -std=gnu++17 -fPIC -MD -MT tools/qcatool/CMakeFiles/qcatool-qt6.dir/main.cpp.o -MF tools/qcatool/CMakeFiles/qcatool-qt6.dir/main.cpp.o.d -o tools/qcatool/CMakeFiles/qcatool-qt6.dir/main.cpp.o -c /var/tmp/portage/app-crypt/qca-2.3.9/work/qca-2.3.9/tools/qcatool/main.cpp
ninja: build stopped: subcommand failed.
 * ERROR: app-crypt/qca-2.3.9::libressl failed (compile phase):
 *   ninja -v -j20 -l21 failed
 *
 * Call stack:
 *     ebuild.sh, line  136:  Called src_compile
 *   environment, line 2395:  Called multibuild_foreach_variant 'cmake_src_compile'
 *   environment, line 1942:  Called _multibuild_run 'cmake_src_compile'
 *   environment, line 1940:  Called cmake_src_compile
 *   environment, line  895:  Called cmake_build
 *   environment, line  862:  Called eninja
 *   environment, line 1344:  Called die
 * The specific snippet of code:
 *       "$@" || die -n "${*} failed"
 *
 * If you need support, post the output of `emerge --info '=app-crypt/qca-2.3.9::libressl'`,
 * the complete build log and the output of `emerge -pqv '=app-crypt/qca-2.3.9::libressl'`.
 * The complete build log is located at '/var/tmp/portage/app-crypt/qca-2.3.9/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-crypt/qca-2.3.9/temp/environment'.
 * Working directory: '/var/tmp/portage/app-crypt/qca-2.3.9/work/qca-2.3.9_build-qt6'
 * S: '/var/tmp/portage/app-crypt/qca-2.3.9/work/qca-2.3.9'
```
Much appreciated.

**Comment by orbea** [comment]
It should be fixed now, thanks again for the report!

**Comment by blucybrb14de** [comment]
I just removed, and re-synced the repository, and it looks like I'm still having the same error. Not sure if the patch works for anyone else. Is anyone able to confirm this?

**Comment by orbea** [comment]
Sometimes it takes time for the github mirror to sync after pushing. Can you confirm the md5sum for the patch?
```
0b9be818df29621d8be665dfb85e64ec  files/qca-2.3.4-libressl.patch
```

**Comment by blucybrb14de** [comment]
After re-syncing again, it looks like the patch worked successfully, thank you.
