### ISSUE TITLE
net-wireless/crda-4.14: undefined symbol: EVP_DigestVerify

### ISSUE THREAD

**Issue by orbea** [gentoo/libressl#335]
The build fails:
```
make LIBTOOL=rlibtool -j4 PREFIX=/usr SBINDIR=$(PREFIX)/sbin/ LIBDIR=$(PREFIX)/lib64 UDEV_RULE_DIR=/lib/udev/rules.d REG_BIN=/usr/lib/crda/regulatory.bin USE_OPENSSL=1 CC=x86_64-pc-linux-gnu-gcc V=1 WERROR= all_noverify 
./utils/key2pub.py pubkeys/linville.key.pub.pem pubkeys/sforshee.key.pub.pem keys.c
Traceback (most recent call last):
  File "./utils/key2pub.py", line 5, in <module>
    from M2Crypto import RSA
  File "/usr/lib/python3.8/site-packages/M2Crypto/__init__.py", line 26, in <module>
    from M2Crypto import (ASN1, AuthCookie, BIO, BN, DH, DSA, EVP, Engine, Err,
  File "/usr/lib/python3.8/site-packages/M2Crypto/ASN1.py", line 15, in <module>
    from M2Crypto import BIO, m2, six
  File "/usr/lib/python3.8/site-packages/M2Crypto/BIO.py", line 11, in <module>
    from M2Crypto import m2, six
  File "/usr/lib/python3.8/site-packages/M2Crypto/m2.py", line 30, in <module>
    from M2Crypto.m2crypto import *
  File "/usr/lib/python3.8/site-packages/M2Crypto/m2crypto.py", line 13, in <module>
    from ._m2crypto import *
ImportError: /usr/lib/python3.8/site-packages/M2Crypto/_m2crypto.cpython-38-x86_64-linux-gnu.so: undefined symbol: EVP_DigestVerify

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./utils/key2pub.py", line 7, in <module>
    sys.stderr.write('ERROR: Failed to import the "M2Crypto" module: %s
' % e.message)
AttributeError: 'ImportError' object has no attribute 'message'
make: *** [Makefile:114: keys.c] Error 1
```
Build log: [build.log](https://github.com/gentoo/libressl/files/6418067/build.log)

The file `/usr/lib/python3.8/site-packages/M2Crypto/_m2crypto.cpython-38-x86_64-linux-gnu.so` is from `dev-python/m2crypto-0.37.1-r1::gentoo` and rebuilding it with the removed libressl patch did not help.

https://gitweb.gentoo.org/repo/gentoo.git/commit/dev-python/m2crypto?id=66e9b462235af21833f09045c272c11e7b63d938

**Comment by orbea** [comment]
This is clearly an issue in m2crypto and the attached patch allows m2crypto to compile without implicitly declared functions and for crda to compile successfully. However I am not sure how correct it is?

[m2crypto-libressl.patch.txt](https://github.com/gentoo/libressl/files/6419470/m2crypto-libressl.patch.txt)

**Comment by CaseOf** [comment]
Ah, with that patch, I know what it is about.
It's about BIO that is not implemented on libressl yet. I had the same issue in qtnetwork that was partially solved by not building dtls

**Comment by orbea** [comment]
I found several issues:

* No ` BIO_get_init()`, solved by using define that already exists for older openssl versions.
* No `EVP_DigestSign()` or `EVP_DigestVerify()`, solved by using `EVP_DigestSignUpdate()`, EVP_DigestSignFinal()`, `EVP_DigestVerifyUpdate()` and `EVP_DigestVerifyFinal()` instead.
* No `OPENSSL_zalloc()`, I used `OPENSSL_malloc()` and `memset()` instead.

I don't really know what I'm doing here so I could of done something wrong?

**Comment by orbea** [comment]
I now realize that I was building the version from `::gentoo` even though the ebuild already exists in `::libressl`, probably because of differences in keywords? Additionally this is only a problem with m2crypto-0.37.1:
```
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * SWIG/_m2crypto_wrap.c:6387:10: warning: implicit declaration of function ‘EVP_DigestSign’; did you mean ‘EVP_DigestSignInit’? [-Wimplicit-function-declaration]
 * SWIG/_m2crypto_wrap.c:6451:12: warning: implicit declaration of function ‘EVP_DigestVerify’; did you mean ‘EVP_DigestVerifyInit’? [-Wimplicit-function-declaration]
```

**Comment by CaseOf** [comment]
does it work on 0.38?

**Comment by CaseOf** [comment]
something you maybe want to know, crda builds fine with dev-python/m2crypto-0.36.0-r1::libressl

**Comment by orbea** [comment]
`m2crypto-0.38.0` currently in gentoo still fails with `libressl-3.4.0`.

**Comment by itZzenXX** [comment]
This patch may not be needed anymore by looking at the LibreSSL 3.4.1 patch notes for OpenBSD 7.0, EVP_DigestVerify is one of the added ABIs. I will test to see if m2crypto builds correctly once it releases. (https://www.openbsd.org/70.html)
